// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/rest-mocking/mocking-responses/stub-response.mdx?collection=docs"
import * as __fd_glob_67 from "../content/docs/rest-mocking/mocking-responses/streaming.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/rest-mocking/mocking-responses/schema-first-mocking.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/rest-mocking/mocking-responses/response-delay.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/rest-mocking/mocking-responses/resolver-params.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/rest-mocking/mocking-responses/request-settings.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/rest-mocking/mocking-responses/redirects.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/rest-mocking/mocking-responses/polling.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/rest-mocking/mocking-responses/file-responses.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/rest-mocking/mocking-responses/error-responses.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/rest-mocking/mocking-responses/cookies.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/rest-mocking/intercepting-requests/request-cookies.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/rest-mocking/intercepting-requests/request-body.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/rest-mocking/intercepting-requests/query-parameters.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/rest-mocking/intercepting-requests/path-parameters.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/rest-mocking/intercepting-requests/index.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/mocking-requests/references/StaticPath.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/mocking-requests/references/Rest.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/mocking-requests/references/MockServerSettings.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/mocking-requests/references/MockServerComponent.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/mocking-requests/references/Logger.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/mocking-requests/references/Interceptors.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/mocking-requests/references/GraphQL.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/mocking-requests/references/Database.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/mocking-requests/references/Cors.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/graphql-mocking/intercepting-operations/variables.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/graphql-mocking/intercepting-operations/operation-name.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/graphql-mocking/intercepting-operations/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/graphql-mocking/mocking-responses/subscriptions.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/graphql-mocking/mocking-responses/stub-response.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/graphql-mocking/mocking-responses/schema-first-mocking.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/graphql-mocking/mocking-responses/response-delay.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/graphql-mocking/mocking-responses/resolver-params.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/graphql-mocking/mocking-responses/request-settings.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/graphql-mocking/mocking-responses/matching.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/graphql-mocking/mocking-responses/error-responses.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/rest-mocking/methods.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/rest-mocking/introduction.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/mocking-requests/static-files.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/mocking-requests/settings.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/mocking-requests/matcher.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/mocking-requests/logger.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/mocking-requests/introducing.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/mocking-requests/cors.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/introduction/what-is-mock-config-server.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/introduction/philosophy.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/introduction/getting-started.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/introduction/comparison.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/cli/run.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/cli/init.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/integrations/nodejs.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/api/start-mock-server.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/api/rest.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api/graphql.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api/create-mock-server.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/graphql-mocking/operations.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/graphql-mocking/introduction.mdx?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/rest-mocking/intercepting-requests/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/mocking-requests/references/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/rest-mocking/mocking-responses/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/graphql-mocking/mocking-responses/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/graphql-mocking/intercepting-operations/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/introduction/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/rest-mocking/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/mocking-requests/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/integrations/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/graphql-mocking/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/api/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "api/meta.json": __fd_glob_1, "graphql-mocking/meta.json": __fd_glob_2, "integrations/meta.json": __fd_glob_3, "mocking-requests/meta.json": __fd_glob_4, "rest-mocking/meta.json": __fd_glob_5, "introduction/meta.json": __fd_glob_6, "graphql-mocking/intercepting-operations/meta.json": __fd_glob_7, "graphql-mocking/mocking-responses/meta.json": __fd_glob_8, "rest-mocking/mocking-responses/meta.json": __fd_glob_9, "mocking-requests/references/meta.json": __fd_glob_10, "rest-mocking/intercepting-requests/meta.json": __fd_glob_11, }, {"graphql-mocking/introduction.mdx": __fd_glob_12, "graphql-mocking/operations.mdx": __fd_glob_13, "api/create-mock-server.mdx": __fd_glob_14, "api/graphql.mdx": __fd_glob_15, "api/rest.mdx": __fd_glob_16, "api/start-mock-server.mdx": __fd_glob_17, "integrations/nodejs.mdx": __fd_glob_18, "cli/init.mdx": __fd_glob_19, "cli/run.mdx": __fd_glob_20, "introduction/comparison.mdx": __fd_glob_21, "introduction/getting-started.mdx": __fd_glob_22, "introduction/philosophy.mdx": __fd_glob_23, "introduction/what-is-mock-config-server.mdx": __fd_glob_24, "mocking-requests/cors.mdx": __fd_glob_25, "mocking-requests/introducing.mdx": __fd_glob_26, "mocking-requests/logger.mdx": __fd_glob_27, "mocking-requests/matcher.mdx": __fd_glob_28, "mocking-requests/settings.mdx": __fd_glob_29, "mocking-requests/static-files.mdx": __fd_glob_30, "rest-mocking/introduction.mdx": __fd_glob_31, "rest-mocking/methods.mdx": __fd_glob_32, "graphql-mocking/mocking-responses/error-responses.mdx": __fd_glob_33, "graphql-mocking/mocking-responses/matching.mdx": __fd_glob_34, "graphql-mocking/mocking-responses/request-settings.mdx": __fd_glob_35, "graphql-mocking/mocking-responses/resolver-params.mdx": __fd_glob_36, "graphql-mocking/mocking-responses/response-delay.mdx": __fd_glob_37, "graphql-mocking/mocking-responses/schema-first-mocking.mdx": __fd_glob_38, "graphql-mocking/mocking-responses/stub-response.mdx": __fd_glob_39, "graphql-mocking/mocking-responses/subscriptions.mdx": __fd_glob_40, "graphql-mocking/intercepting-operations/index.mdx": __fd_glob_41, "graphql-mocking/intercepting-operations/operation-name.mdx": __fd_glob_42, "graphql-mocking/intercepting-operations/variables.mdx": __fd_glob_43, "mocking-requests/references/Cors.mdx": __fd_glob_44, "mocking-requests/references/Database.mdx": __fd_glob_45, "mocking-requests/references/GraphQL.mdx": __fd_glob_46, "mocking-requests/references/Interceptors.mdx": __fd_glob_47, "mocking-requests/references/Logger.mdx": __fd_glob_48, "mocking-requests/references/MockServerComponent.mdx": __fd_glob_49, "mocking-requests/references/MockServerSettings.mdx": __fd_glob_50, "mocking-requests/references/Rest.mdx": __fd_glob_51, "mocking-requests/references/StaticPath.mdx": __fd_glob_52, "rest-mocking/intercepting-requests/index.mdx": __fd_glob_53, "rest-mocking/intercepting-requests/path-parameters.mdx": __fd_glob_54, "rest-mocking/intercepting-requests/query-parameters.mdx": __fd_glob_55, "rest-mocking/intercepting-requests/request-body.mdx": __fd_glob_56, "rest-mocking/intercepting-requests/request-cookies.mdx": __fd_glob_57, "rest-mocking/mocking-responses/cookies.mdx": __fd_glob_58, "rest-mocking/mocking-responses/error-responses.mdx": __fd_glob_59, "rest-mocking/mocking-responses/file-responses.mdx": __fd_glob_60, "rest-mocking/mocking-responses/polling.mdx": __fd_glob_61, "rest-mocking/mocking-responses/redirects.mdx": __fd_glob_62, "rest-mocking/mocking-responses/request-settings.mdx": __fd_glob_63, "rest-mocking/mocking-responses/resolver-params.mdx": __fd_glob_64, "rest-mocking/mocking-responses/response-delay.mdx": __fd_glob_65, "rest-mocking/mocking-responses/schema-first-mocking.mdx": __fd_glob_66, "rest-mocking/mocking-responses/streaming.mdx": __fd_glob_67, "rest-mocking/mocking-responses/stub-response.mdx": __fd_glob_68, });